### ISSUE TITLE
Not working on Android 5 Lollipop

### ISSUE THREAD

**Issue by bastei** [soynerdito/BlueSound#3]
The app does nothing for me on Android Lollipop (CM12).
BTmono does its job for me. But, you know, I like open source.
How can I help fixing the bug?

**Comment by soynerdito** [comment]
You are already helping. If you code you can fork the project and submit a pull request with the fix. If you do not code, you can continue reporting errors and you may create an Issue with a feature you'll like the app to have.
Can you describe how you use BTmono and how you expect this one to work. I have a phone with CM12 that I have not used. I will give it a test.

This app requires the audio to be started before clicking on the button. For example, you need to start your music player and then click on the button.
I was using an app for the market that did the same, but had adds and that's why this one started.

If possible write a short step by step description of what you are doing with results and where the result is not the one expected.

**Comment by soynerdito** [comment]
Confirming the error. Error replicated on CM12. Will be fixed. thanks for the patience.
